# Generated by Django 4.0.7 on 2023-07-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('progress', models.CharField(choices=[('Não iniciado', 'Ni'), ('Em progresso', 'Ep'), ('Concluído', 'Co')], default='Não iniciado', max_length=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
